# Generated by Django 2.1.5 on 2021-01-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='pasta',
            field=models.CharField(max_length=64),
        ),
    ]
