# Generated by Django 2.1.5 on 2021-01-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='Toppings',
            field=models.CharField(max_length=64),
        ),
    ]
