# Generated by Django 2.1.5 on 2021-01-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210117_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='topping_1',
            field=models.ManyToManyField(blank=True, related_name='item1', to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='cart',
            name='topping_2',
            field=models.ManyToManyField(blank=True, related_name='item2', to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='cart',
            name='topping_3',
            field=models.ManyToManyField(blank=True, related_name='item3', to='orders.Toppings'),
        ),
    ]
