# Generated by Django 2.1.5 on 2021-01-20 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20210119_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='topping_1',
        ),
        migrations.AddField(
            model_name='cart',
            name='topping_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item1', to='orders.Toppings'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='topping_2',
        ),
        migrations.AddField(
            model_name='cart',
            name='topping_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item2', to='orders.Toppings'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='topping_3',
        ),
        migrations.AddField(
            model_name='cart',
            name='topping_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item3', to='orders.Toppings'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ManyToManyField(related_name='cart_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
