# Generated by Django 2.1.5 on 2021-01-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210119_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='topping_1',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='topping_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='cart',
            name='topping_3',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
