# Generated by Django 2.1.5 on 2021-01-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210120_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='topping_1',
            new_name='top_1',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='topping_3',
            new_name='top_3',
        ),
    ]
