# Generated by Django 2.1.5 on 2021-01-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210120_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='top_1',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='top_2',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='top_3',
        ),
        migrations.AddField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='topped_items', to='orders.Toppings'),
        ),
    ]
