# Generated by Django 2.1.5 on 2021-01-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210124_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='toppings',
            new_name='toppings_and_extras',
        ),
    ]
