# Generated by Django 2.1.5 on 2021-01-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210124_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.CharField(default='', max_length=64),
        ),
    ]
