# Generated by Django 2.1.5 on 2021-01-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_sub_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='toppings_and_extras',
            new_name='toppings',
        ),
    ]
