# Generated by Django 2.1.5 on 2021-01-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20210124_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='sub_extras',
            field=models.ManyToManyField(blank=True, related_name='extras', to='orders.Sub_Extras'),
        ),
    ]
