# Generated by Django 2.1.5 on 2021-01-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20210130_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='placed_order',
            field=models.BooleanField(default=False),
        ),
    ]
